version: '3.8'

services:
  app:
    container_name: espace-iris-app
    build: .
    restart: always
    network_mode: "host"
    env_file:
      - .env
    volumes:
      - /var/espace-iris-files:/var/espace-iris-files