import { Affiliation, BeneficiaryType } from '../enums';
import { Doctor } from './Doctor';
import { User } from './User';
import { File } from './File';
import { MedicalDevice } from './MedicalDevice';
import { Payment } from './Payment';
import { Diagnostic } from './Diagnostic';
import { Appointment } from './Appointment';
import { Rental } from './Rental';
import { Notification } from './Notification';
import { PatientHistory } from './PatientHistory';

export interface Patient {
  id: string;
  patientCode?: string;
  firstName: string;
  lastName: string;
  telephone: string;
  telephoneTwo?: string;
  generalNote?: string;
  affiliation?: Affiliation;
  antecedant?: string;
  beneficiaryType?: BeneficiaryType;
  address?: string;
  addressCoordinates?: { lat: number; lng: number };
  dateOfBirth?: Date;
  cin?: string;
  cnamId?: string;
  weight?: number;
  height?: number;
  imc?: number;
  medicalHistory?: string;
  doctorId?: string;
  doctor?: Doctor;
  technicianId?: string;
  technician?: User;
  assignedTo: User;
  userId: string;
  files?: File[];
  medicalDevices?: MedicalDevice[];
  payments?: Payment[];
  diagnostics?: Diagnostic[];
  appointments?: Appointment[];
  rentals?: Rental[];
  notifications?: Notification[];
  history?: PatientHistory[];
  createdAt: Date;
  updatedAt: Date;
}
